// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/models/shared"
	"net/http"
)

type DeletePaymentMethodSecurity struct {
	OAuth   string `security:"scheme,type=oauth2,name=Authorization"`
	XAPIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *DeletePaymentMethodSecurity) GetOAuth() string {
	if o == nil {
		return ""
	}
	return o.OAuth
}

func (o *DeletePaymentMethodSecurity) GetXAPIKey() string {
	if o == nil {
		return ""
	}
	return o.XAPIKey
}

type DeletePaymentMethodRequest struct {
	// The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].
	XPublishableKey *string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The ID for a payment method in the shopper's Bolt account Wallet. This ID can be obtained using [Get Account Details](#tag/Account/operation/GetAccountDetails).
	PaymentMethodID string `pathParam:"style=simple,explode=false,name=payment_method_id"`
}

func (o *DeletePaymentMethodRequest) GetXPublishableKey() *string {
	if o == nil {
		return nil
	}
	return o.XPublishableKey
}

func (o *DeletePaymentMethodRequest) GetPaymentMethodID() string {
	if o == nil {
		return ""
	}
	return o.PaymentMethodID
}

type DeletePaymentMethodResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Forbidden
	ErrorsBoltAPIResponse *shared.ErrorsBoltAPIResponse
}

func (o *DeletePaymentMethodResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeletePaymentMethodResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeletePaymentMethodResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeletePaymentMethodResponse) GetErrorsBoltAPIResponse() *shared.ErrorsBoltAPIResponse {
	if o == nil {
		return nil
	}
	return o.ErrorsBoltAPIResponse
}
