// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/models/shared"
	"net/http"
)

type OAuthTokenRequestBodyType string

const (
	OAuthTokenRequestBodyTypeOAuthTokenInput2        OAuthTokenRequestBodyType = "o_auth_token_input2"
	OAuthTokenRequestBodyTypeOAuthTokenInputRefresh1 OAuthTokenRequestBodyType = "o_auth_token_input_refresh1"
)

type OAuthTokenRequestBody struct {
	OAuthTokenInput2        *shared.OAuthTokenInput2
	OAuthTokenInputRefresh1 *shared.OAuthTokenInputRefresh1

	Type OAuthTokenRequestBodyType
}

func CreateOAuthTokenRequestBodyOAuthTokenInput2(oAuthTokenInput2 shared.OAuthTokenInput2) OAuthTokenRequestBody {
	typ := OAuthTokenRequestBodyTypeOAuthTokenInput2

	return OAuthTokenRequestBody{
		OAuthTokenInput2: &oAuthTokenInput2,
		Type:             typ,
	}
}

func CreateOAuthTokenRequestBodyOAuthTokenInputRefresh1(oAuthTokenInputRefresh1 shared.OAuthTokenInputRefresh1) OAuthTokenRequestBody {
	typ := OAuthTokenRequestBodyTypeOAuthTokenInputRefresh1

	return OAuthTokenRequestBody{
		OAuthTokenInputRefresh1: &oAuthTokenInputRefresh1,
		Type:                    typ,
	}
}

func (u *OAuthTokenRequestBody) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	oAuthTokenInput2 := new(shared.OAuthTokenInput2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&oAuthTokenInput2); err == nil {
		u.OAuthTokenInput2 = oAuthTokenInput2
		u.Type = OAuthTokenRequestBodyTypeOAuthTokenInput2
		return nil
	}

	oAuthTokenInputRefresh1 := new(shared.OAuthTokenInputRefresh1)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&oAuthTokenInputRefresh1); err == nil {
		u.OAuthTokenInputRefresh1 = oAuthTokenInputRefresh1
		u.Type = OAuthTokenRequestBodyTypeOAuthTokenInputRefresh1
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u OAuthTokenRequestBody) MarshalJSON() ([]byte, error) {
	if u.OAuthTokenInput2 != nil {
		return json.Marshal(u.OAuthTokenInput2)
	}

	if u.OAuthTokenInputRefresh1 != nil {
		return json.Marshal(u.OAuthTokenInputRefresh1)
	}

	return nil, errors.New("could not marshal union type: all fields are null")

}

type OAuthTokenRequest struct {
	RequestBody *OAuthTokenRequestBody `request:"mediaType=application/x-www-form-urlencoded"`
	// The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].
	XPublishableKey *string `header:"style=simple,explode=false,name=X-Publishable-Key"`
}

func (o *OAuthTokenRequest) GetRequestBody() *OAuthTokenRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *OAuthTokenRequest) GetXPublishableKey() *string {
	if o == nil {
		return nil
	}
	return o.XPublishableKey
}

type OAuthTokenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Invalid request to OAuth Token.
	ErrorsOauthServerResponse *shared.ErrorsOauthServerResponse
	// OAuth token response.
	OAuthTokenResponse *shared.OAuthTokenResponse
}

func (o *OAuthTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OAuthTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OAuthTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OAuthTokenResponse) GetErrorsOauthServerResponse() *shared.ErrorsOauthServerResponse {
	if o == nil {
		return nil
	}
	return o.ErrorsOauthServerResponse
}

func (o *OAuthTokenResponse) GetOAuthTokenResponse() *shared.OAuthTokenResponse {
	if o == nil {
		return nil
	}
	return o.OAuthTokenResponse
}
