// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AddressChangeView struct {
	// The address object returned in the response.
	FromAddress *AddressView `json:"from_address,omitempty"`
	Status      *string      `json:"status,omitempty"`
	TicketID    *string      `json:"ticket_id,omitempty"`
	Timestamp   *float64     `json:"timestamp,omitempty"`
	// The address object returned in the response.
	ToAddress *AddressView `json:"to_address,omitempty"`
}

func (o *AddressChangeView) GetFromAddress() *AddressView {
	if o == nil {
		return nil
	}
	return o.FromAddress
}

func (o *AddressChangeView) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *AddressChangeView) GetTicketID() *string {
	if o == nil {
		return nil
	}
	return o.TicketID
}

func (o *AddressChangeView) GetTimestamp() *float64 {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *AddressChangeView) GetToAddress() *AddressView {
	if o == nil {
		return nil
	}
	return o.ToAddress
}
