// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddressView - The address object returned in the response.
type AddressView struct {
	// The company name associated with this address.
	Company *string `json:"company,omitempty"`
	// The name of the country associated with this address.
	Country *string `json:"country,omitempty"`
	// The ISO 3166-1 alpha-2 country code associated with this address.
	CountryCode *string `json:"country_code,omitempty"`
	// The building door code or community gate code.
	DoorCode *string `json:"door_code,omitempty"`
	// An email address.
	EmailAddress *string `json:"email_address,omitempty"`
	// The given name of the person associated with this address.
	FirstName *string `json:"first_name,omitempty"`
	// The unique Bolt ID associated with this address.
	ID *string `json:"id,omitempty"`
	// The surname of the person associated with this address.
	LastName *string `json:"last_name,omitempty"`
	// The city name details associated with this address.
	Locality *string `json:"locality,omitempty"`
	// The given and surname of the person associated with this address.
	Name *string `json:"name,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// The postal or zip code associated with this address.
	PostalCode *string `json:"postal_code,omitempty"`
	// The region details such as state or province associated with this address.
	Region *string `json:"region,omitempty"`
	// The the ISO 3166-2 region code associated with this address.
	RegionCode *string `json:"region_code,omitempty"`
	// The street number and street name of the address.
	StreetAddress1 *string `json:"street_address1,omitempty"`
	// Any apartment, floor, or unit details.
	StreetAddress2 *string `json:"street_address2,omitempty"`
	// Any additional street address details.
	StreetAddress3 *string `json:"street_address3,omitempty"`
	// Any additional street address details.
	StreetAddress4 *string `json:"street_address4,omitempty"`
}

func (o *AddressView) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *AddressView) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *AddressView) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *AddressView) GetDoorCode() *string {
	if o == nil {
		return nil
	}
	return o.DoorCode
}

func (o *AddressView) GetEmailAddress() *string {
	if o == nil {
		return nil
	}
	return o.EmailAddress
}

func (o *AddressView) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *AddressView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AddressView) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *AddressView) GetLocality() *string {
	if o == nil {
		return nil
	}
	return o.Locality
}

func (o *AddressView) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AddressView) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *AddressView) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *AddressView) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressView) GetRegionCode() *string {
	if o == nil {
		return nil
	}
	return o.RegionCode
}

func (o *AddressView) GetStreetAddress1() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress1
}

func (o *AddressView) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}

func (o *AddressView) GetStreetAddress3() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress3
}

func (o *AddressView) GetStreetAddress4() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress4
}
