// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// The Address object is used for billing, shipping, and physical store address use cases.
type Address struct {
	// The company name associated with this address.
	Company *string `json:"company,omitempty"`
	// The name of the country associated with this address.
	Country *string `json:"country,omitempty"`
	// The ISO 3166-1 alpha-2 country code associated with this address.
	CountryCode string `json:"country_code"`
	// Whether the added address is now the default address.
	Default *bool `json:"default,omitempty"`
	// The building door code or community gate code.
	DoorCode *string `json:"door_code,omitempty"`
	// An email address.
	Email string `json:"email"`
	// The given name of the person associated with this address.
	FirstName string `json:"first_name"`
	// The surname of the person associated with this address.
	LastName string `json:"last_name"`
	// The city name details associated with this address.
	Locality string `json:"locality"`
	// The given and surname of the person associated with this address.
	Name *string `json:"name,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	Phone *string `json:"phone,omitempty"`
	// The the postal or zip code associated with this address.
	PostalCode string `json:"postal_code"`
	// **Not Required for NON US addresses**. The region details such as state or province associated with this address.
	Region string `json:"region"`
	// The ISO 3166-2 region code associated with this address.
	//   - * If specified, value must be valid for the `country`.
	//   - * If null, value is inferred from the `region`.
	//
	RegionCode *string `json:"region_code,omitempty"`
	// The street number and street name of the address.
	StreetAddress1 string `json:"street_address1"`
	// Any apartment, floor, or unit details.
	StreetAddress2 *string `json:"street_address2,omitempty"`
	// Any additional street address details.
	StreetAddress3 *string `json:"street_address3,omitempty"`
	// Any additional street address details.
	StreetAddress4 *string `json:"street_address4,omitempty"`
}

func (o *Address) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *Address) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *Address) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *Address) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *Address) GetDoorCode() *string {
	if o == nil {
		return nil
	}
	return o.DoorCode
}

func (o *Address) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *Address) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *Address) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *Address) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *Address) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Address) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *Address) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *Address) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *Address) GetRegionCode() *string {
	if o == nil {
		return nil
	}
	return o.RegionCode
}

func (o *Address) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *Address) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}

func (o *Address) GetStreetAddress3() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress3
}

func (o *Address) GetStreetAddress4() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress4
}
