// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Amounts - The amount. **Nullable** for Transactions Details.
type Amounts struct {
	// The amount in cents. **Nullable** for Transactions Details.
	Amount int64 `json:"amount"`
	// The 3-digit ISO code for the currency. **Nullable** for Transactions Details.
	Currency string `json:"currency"`
	// The currency symbol used for the amount. **Nullable** for Transactions Details.
	CurrencySymbol string `json:"currency_symbol"`
}

func (o *Amounts) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Amounts) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *Amounts) GetCurrencySymbol() string {
	if o == nil {
		return ""
	}
	return o.CurrencySymbol
}
