// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartItemProperty struct {
	Color   *string  `json:"color,omitempty"`
	Display *bool    `json:"display,omitempty"`
	Name    *string  `json:"name,omitempty"`
	NameID  *float64 `json:"name_id,omitempty"`
	Value   *string  `json:"value,omitempty"`
	ValueID *float64 `json:"value_id,omitempty"`
}

func (o *CartItemProperty) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *CartItemProperty) GetDisplay() *bool {
	if o == nil {
		return nil
	}
	return o.Display
}

func (o *CartItemProperty) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CartItemProperty) GetNameID() *float64 {
	if o == nil {
		return nil
	}
	return o.NameID
}

func (o *CartItemProperty) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *CartItemProperty) GetValueID() *float64 {
	if o == nil {
		return nil
	}
	return o.ValueID
}
