// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartLoyaltyRewards struct {
	// The reward amount in cents (1/100).
	Amount *float64 `json:"amount,omitempty"`
	// The loyalty reward's coupon code.
	CouponCode *string `json:"coupon_code,omitempty"`
	// A description of the loyalty reward that will be shown to the shopper.
	Description *string `json:"description,omitempty"`
	// Internal-facing metadata for the Loyalty Rewards. Ideal for adding any other identifying information about the reward,  including a duplication of the original loyalty reward json response from the loyalty provider as shown in the example provided. If you choose to use this field  to hold json, enclose the content in single quotes to force a string value.
	Details *string `json:"details,omitempty"`
	// The number of points needed for this reward.
	Points *float64 `json:"points,omitempty"`
	// The loyalty rewards provider.
	Source *string `json:"source,omitempty"`
	// The type of loyalty reward.
	Type *string `json:"type,omitempty"`
}

func (o *CartLoyaltyRewards) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CartLoyaltyRewards) GetCouponCode() *string {
	if o == nil {
		return nil
	}
	return o.CouponCode
}

func (o *CartLoyaltyRewards) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CartLoyaltyRewards) GetDetails() *string {
	if o == nil {
		return nil
	}
	return o.Details
}

func (o *CartLoyaltyRewards) GetPoints() *float64 {
	if o == nil {
		return nil
	}
	return o.Points
}

func (o *CartLoyaltyRewards) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *CartLoyaltyRewards) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
