// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CartShipment - A cart that is being prepared for shipment
type CartShipment struct {
	// The name of the carrier selected.
	Carrier *string `json:"carrier,omitempty"`
	// The cost in cents.
	Cost *int64 `json:"cost,omitempty"`
	// Defines if shopper has a membership discount.
	DiscountedByMembership *bool `json:"discounted_by_membership,omitempty"`
	// The estimated delivery date.
	EstimatedDeliveryDate *string `json:"estimated_delivery_date,omitempty"`
	// True if shipment is expedited.
	Expedited *bool `json:"expedited,omitempty"`
	// The depth.
	PackageDepth *int64 `json:"package_depth,omitempty"`
	// The unit of measurement for an item's dimensions.
	PackageDimensionUnit *string `json:"package_dimension_unit,omitempty"`
	// The height.
	PackageHeight *int64 `json:"package_height,omitempty"`
	// The type of package.
	PackageType *string `json:"package_type,omitempty"`
	// The unit of measurement for an item's weight.
	PackageWeightUnit *string `json:"package_weight_unit,omitempty"`
	// The width.
	PackageWidth *int64 `json:"package_width,omitempty"`
	// The service name.
	Service *string `json:"service,omitempty"`
	// The Address object is used for billing, shipping, and physical store address use cases.
	ShippingAddress *Address `json:"shipping_address,omitempty"`
	// ID for billing address
	ShippingAddressID *string `json:"shipping_address_id,omitempty"`
	// The name of the shipping method.
	ShippingMethod *string `json:"shipping_method,omitempty"`
	// The signature.
	Signature *string `json:"signature,omitempty"`
	// Tax amount in cents.
	TaxAmount *int64 `json:"tax_amount,omitempty"`
	// The relevant tax code.
	TaxCode *string `json:"tax_code,omitempty"`
	// The total weight.
	TotalWeight *int64 `json:"total_weight,omitempty"`
	// The unit of measurement for an item's weight.
	TotalWeightUnit *string `json:"total_weight_unit,omitempty"`
	// The type corresponding to this shipment, if applicable.
	Type *CartShipmentType `json:"type,omitempty"`
}

func (o *CartShipment) GetCarrier() *string {
	if o == nil {
		return nil
	}
	return o.Carrier
}

func (o *CartShipment) GetCost() *int64 {
	if o == nil {
		return nil
	}
	return o.Cost
}

func (o *CartShipment) GetDiscountedByMembership() *bool {
	if o == nil {
		return nil
	}
	return o.DiscountedByMembership
}

func (o *CartShipment) GetEstimatedDeliveryDate() *string {
	if o == nil {
		return nil
	}
	return o.EstimatedDeliveryDate
}

func (o *CartShipment) GetExpedited() *bool {
	if o == nil {
		return nil
	}
	return o.Expedited
}

func (o *CartShipment) GetPackageDepth() *int64 {
	if o == nil {
		return nil
	}
	return o.PackageDepth
}

func (o *CartShipment) GetPackageDimensionUnit() *string {
	if o == nil {
		return nil
	}
	return o.PackageDimensionUnit
}

func (o *CartShipment) GetPackageHeight() *int64 {
	if o == nil {
		return nil
	}
	return o.PackageHeight
}

func (o *CartShipment) GetPackageType() *string {
	if o == nil {
		return nil
	}
	return o.PackageType
}

func (o *CartShipment) GetPackageWeightUnit() *string {
	if o == nil {
		return nil
	}
	return o.PackageWeightUnit
}

func (o *CartShipment) GetPackageWidth() *int64 {
	if o == nil {
		return nil
	}
	return o.PackageWidth
}

func (o *CartShipment) GetService() *string {
	if o == nil {
		return nil
	}
	return o.Service
}

func (o *CartShipment) GetShippingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.ShippingAddress
}

func (o *CartShipment) GetShippingAddressID() *string {
	if o == nil {
		return nil
	}
	return o.ShippingAddressID
}

func (o *CartShipment) GetShippingMethod() *string {
	if o == nil {
		return nil
	}
	return o.ShippingMethod
}

func (o *CartShipment) GetSignature() *string {
	if o == nil {
		return nil
	}
	return o.Signature
}

func (o *CartShipment) GetTaxAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.TaxAmount
}

func (o *CartShipment) GetTaxCode() *string {
	if o == nil {
		return nil
	}
	return o.TaxCode
}

func (o *CartShipment) GetTotalWeight() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalWeight
}

func (o *CartShipment) GetTotalWeightUnit() *string {
	if o == nil {
		return nil
	}
	return o.TotalWeightUnit
}

func (o *CartShipment) GetType() *CartShipmentType {
	if o == nil {
		return nil
	}
	return o.Type
}
