// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CartAddOn - A list of up to 3 add-ons that are displayed to the shopper.
type CartAddOn struct {
	// The description of the product being displayed as an add on.
	Description *string `json:"description,omitempty"`
	// The URL of the image displayed for the add on product.
	ImageURL *string `json:"imageUrl,omitempty"`
	// The name of the product being displayed as an add on.
	Name string `json:"name"`
	// The price of the product add on in cents (1/100).
	Price float64 `json:"price"`
	// The the ID of the product being displayed as an add on.
	ProductID string `json:"productId"`
	// The URL to the product page of the product being displayed as an add on.
	ProductPageURL *string `json:"productPageUrl,omitempty"`
}

func (o *CartAddOn) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CartAddOn) GetImageURL() *string {
	if o == nil {
		return nil
	}
	return o.ImageURL
}

func (o *CartAddOn) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CartAddOn) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *CartAddOn) GetProductID() string {
	if o == nil {
		return ""
	}
	return o.ProductID
}

func (o *CartAddOn) GetProductPageURL() *string {
	if o == nil {
		return nil
	}
	return o.ProductPageURL
}
