// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type DiscountCategory string

const (
	DiscountCategoryCoupon               DiscountCategory = "coupon"
	DiscountCategoryGiftcard             DiscountCategory = "giftcard"
	DiscountCategoryManagedGiftcard      DiscountCategory = "managed_giftcard"
	DiscountCategoryStoreCredit          DiscountCategory = "store_credit"
	DiscountCategoryAutomaticPromotion   DiscountCategory = "automatic_promotion"
	DiscountCategoryMembershipDiscount   DiscountCategory = "membership_discount"
	DiscountCategoryMembershipGiftcard   DiscountCategory = "membership_giftcard"
	DiscountCategorySubscriptionDiscount DiscountCategory = "subscription_discount"
	DiscountCategoryRewardsDiscount      DiscountCategory = "rewards_discount"
	DiscountCategoryUnknown              DiscountCategory = "unknown"
)

func (e DiscountCategory) ToPointer() *DiscountCategory {
	return &e
}

func (e *DiscountCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "coupon":
		fallthrough
	case "giftcard":
		fallthrough
	case "managed_giftcard":
		fallthrough
	case "store_credit":
		fallthrough
	case "automatic_promotion":
		fallthrough
	case "membership_discount":
		fallthrough
	case "membership_giftcard":
		fallthrough
	case "subscription_discount":
		fallthrough
	case "rewards_discount":
		fallthrough
	case "unknown":
		*e = DiscountCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DiscountCategory: %v", v)
	}
}

// Type - The type of discount.
type Type string

const (
	TypeFixedAmount  Type = "fixed_amount"
	TypePercentage   Type = "percentage"
	TypeFreeShipping Type = "free_shipping"
)

func (e Type) ToPointer() *Type {
	return &e
}

func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fixed_amount":
		fallthrough
	case "percentage":
		fallthrough
	case "free_shipping":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type CartDiscount struct {
	Amount *float64 `json:"amount,omitempty"`
	Code   *string  `json:"code,omitempty"`
	// Used to define the discount offering.
	Description *string `json:"description,omitempty"`
	// Used to provide a link to additional details, such as a landing page, associated with the discount offering.
	DetailsURL       *string           `json:"details_url,omitempty"`
	DiscountCategory *DiscountCategory `json:"discount_category,omitempty"`
	// Used to define the reference ID associated with the discount available.
	Reference *string `json:"reference,omitempty"`
	// The type of discount.
	Type *Type `json:"type,omitempty"`
}

func (o *CartDiscount) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CartDiscount) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CartDiscount) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CartDiscount) GetDetailsURL() *string {
	if o == nil {
		return nil
	}
	return o.DetailsURL
}

func (o *CartDiscount) GetDiscountCategory() *DiscountCategory {
	if o == nil {
		return nil
	}
	return o.DiscountCategory
}

func (o *CartDiscount) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *CartDiscount) GetType() *Type {
	if o == nil {
		return nil
	}
	return o.Type
}
