// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ChargebackDetails struct {
	AmtWon        *AmountView `json:"amt_won,omitempty"`
	ChargebackAmt *AmountView `json:"chargeback_amt,omitempty"`
	ChargebackFee *AmountView `json:"chargeback_fee,omitempty"`
	// The unique ID of the chargeback.
	ChargebackID *string               `json:"chargeback_id,omitempty"`
	EventViews   []ChargebackEventView `json:"event_views,omitempty"`
	NetAmt       *AmountView           `json:"net_amt,omitempty"`
	// The reason for the chargeback.
	Reason *string `json:"reason,omitempty"`
	// Bolt's [standardized reason codes](https://help.bolt.com/merchants/references/policies/disputes/dispute-codes/).
	ReasonCode *ChargebackReasonCode `json:"reason_code,omitempty"`
	// The date of the chargeback.
	RepresentmentReplyByDate *int64 `json:"representment_reply_by_date,omitempty"`
	// The result of the chargeback representment.
	RepresentmentResult *ChargebackRepresentmentResult `json:"representment_result,omitempty"`
}

func (o *ChargebackDetails) GetAmtWon() *AmountView {
	if o == nil {
		return nil
	}
	return o.AmtWon
}

func (o *ChargebackDetails) GetChargebackAmt() *AmountView {
	if o == nil {
		return nil
	}
	return o.ChargebackAmt
}

func (o *ChargebackDetails) GetChargebackFee() *AmountView {
	if o == nil {
		return nil
	}
	return o.ChargebackFee
}

func (o *ChargebackDetails) GetChargebackID() *string {
	if o == nil {
		return nil
	}
	return o.ChargebackID
}

func (o *ChargebackDetails) GetEventViews() []ChargebackEventView {
	if o == nil {
		return nil
	}
	return o.EventViews
}

func (o *ChargebackDetails) GetNetAmt() *AmountView {
	if o == nil {
		return nil
	}
	return o.NetAmt
}

func (o *ChargebackDetails) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *ChargebackDetails) GetReasonCode() *ChargebackReasonCode {
	if o == nil {
		return nil
	}
	return o.ReasonCode
}

func (o *ChargebackDetails) GetRepresentmentReplyByDate() *int64 {
	if o == nil {
		return nil
	}
	return o.RepresentmentReplyByDate
}

func (o *ChargebackDetails) GetRepresentmentResult() *ChargebackRepresentmentResult {
	if o == nil {
		return nil
	}
	return o.RepresentmentResult
}
