// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateAccountInput - The details needed to create a Bolt account.
type CreateAccountInput struct {
	// A list of physical shipping addresses associated with this account.
	Addresses []AddressAccount `json:"addresses,omitempty"`
	// A list of payment methods associated with this account.
	PaymentMethods []PaymentMethodAccount `json:"payment_methods,omitempty"`
	// The first name, last name, email address, and phone number of a shopper.
	Profile Profile `json:"profile"`
}

func (o *CreateAccountInput) GetAddresses() []AddressAccount {
	if o == nil {
		return nil
	}
	return o.Addresses
}

func (o *CreateAccountInput) GetPaymentMethods() []PaymentMethodAccount {
	if o == nil {
		return nil
	}
	return o.PaymentMethods
}

func (o *CreateAccountInput) GetProfile() Profile {
	if o == nil {
		return Profile{}
	}
	return o.Profile
}
