// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreditCardUser - The credit card user.
type CreditCardUser struct {
	// A list of email addresses. **Nullable** for Transactions Details.
	Emails []Emails `json:"emails,omitempty"`
	// The person's first name.
	FirstName *string `json:"first_name,omitempty"`
	// The shopper's unique ID.
	ID *string `json:"id,omitempty"`
	// The person's last name.
	LastName *string `json:"last_name,omitempty"`
	// A list of phone numbers.
	Phones []PhonesWithCountryCode `json:"phones,omitempty"`
}

func (o *CreditCardUser) GetEmails() []Emails {
	if o == nil {
		return nil
	}
	return o.Emails
}

func (o *CreditCardUser) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *CreditCardUser) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreditCardUser) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *CreditCardUser) GetPhones() []PhonesWithCountryCode {
	if o == nil {
		return nil
	}
	return o.Phones
}
