// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreditCardView - Contains details about the credit card transaction.
type CreditCardView struct {
	// The address object returned in the response.
	BillingAddress *AddressView `json:"billing_address,omitempty"`
	// The Bank Identification Number for the credit card; this is typically the first 4-6 digits of the credit card number. **Nullable** for Transactions Details.
	Bin *string `json:"bin,omitempty"`
	// The card's network. **Nullable** for Transactions Details.
	DisplayNetwork *CardDisplayNetwork `json:"display_network,omitempty"`
	// The card's expiration. **Nullable** for Transactions Details.
	Expiration *int64 `json:"expiration,omitempty"`
	// The asset link for displayed icons. This link varies depending on payment method used.  **Nullable** for Transactions Details.
	IconAssetPath *string `json:"icon_asset_path,omitempty"`
	// The card's ID. **Nullable** for Transactions Details.
	ID *string `json:"id,omitempty"`
	// The card's last 4 digits. **Nullable** for Transactions Details.
	Last4 *string `json:"last4,omitempty"`
	// The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard
	//
	Network *CardNetwork `json:"network,omitempty"`
	// Describes the card's priority.
	//
	Priority *Priority `json:"priority,omitempty"`
	// The card's status. **Nullable** for Transactions Details.
	Status *CardStatus `json:"status,omitempty"`
	// The Bolt token associated to the credit card. Required for new, unsaved cards.
	Token *string `json:"token,omitempty"`
	// Used to define which payment processor generated the token for this credit card.
	//
	TokenType *CardTokenType `json:"token_type,omitempty"`
}

func (o *CreditCardView) GetBillingAddress() *AddressView {
	if o == nil {
		return nil
	}
	return o.BillingAddress
}

func (o *CreditCardView) GetBin() *string {
	if o == nil {
		return nil
	}
	return o.Bin
}

func (o *CreditCardView) GetDisplayNetwork() *CardDisplayNetwork {
	if o == nil {
		return nil
	}
	return o.DisplayNetwork
}

func (o *CreditCardView) GetExpiration() *int64 {
	if o == nil {
		return nil
	}
	return o.Expiration
}

func (o *CreditCardView) GetIconAssetPath() *string {
	if o == nil {
		return nil
	}
	return o.IconAssetPath
}

func (o *CreditCardView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreditCardView) GetLast4() *string {
	if o == nil {
		return nil
	}
	return o.Last4
}

func (o *CreditCardView) GetNetwork() *CardNetwork {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *CreditCardView) GetPriority() *Priority {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *CreditCardView) GetStatus() *CardStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreditCardView) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *CreditCardView) GetTokenType() *CardTokenType {
	if o == nil {
		return nil
	}
	return o.TokenType
}
