// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/utils"
)

// CreditCardPriority - Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
type CreditCardPriority int64

const (
	CreditCardPriorityOne CreditCardPriority = 1
	CreditCardPriorityTwo CreditCardPriority = 2
)

func (e CreditCardPriority) ToPointer() *CreditCardPriority {
	return &e
}

func (e *CreditCardPriority) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		*e = CreditCardPriority(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreditCardPriority: %v", v)
	}
}

// CreditCard - The credit_card object is used to to pay for guest-checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions. Add `billing_address` to this if storing a billing address for a returning shopper.
type CreditCard struct {
	// The Address object is used for billing, shipping, and physical store address use cases.
	BillingAddress *Address `json:"billing_address,omitempty"`
	// The Bank Identification Number for the credit card; this is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The expiration date of the credit card.
	Expiration string `json:"expiration"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// Used for the postal or zip code associated with the credit card.
	PostalCode string `json:"postal_code"`
	// Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
	Priority *CreditCardPriority `json:"priority,omitempty"`
	// Determines whether or not the credit card will be saved to the shopper's account. Defaults to `true`.
	Save *bool `json:"save,omitempty"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
	// Used to define which payment processor generated the token for this credit card; for those using Bolt's tokenizer, the value must be `bolt`.
	tokenType string `const:"bolt" json:"token_type"`
}

func (c CreditCard) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditCard) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreditCard) GetBillingAddress() *Address {
	if o == nil {
		return nil
	}
	return o.BillingAddress
}

func (o *CreditCard) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *CreditCard) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *CreditCard) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *CreditCard) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *CreditCard) GetPriority() *CreditCardPriority {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *CreditCard) GetSave() *bool {
	if o == nil {
		return nil
	}
	return o.Save
}

func (o *CreditCard) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *CreditCard) GetTokenType() string {
	return "bolt"
}
