// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreditCardCaptureView struct {
	Amount *AmountView `json:"amount,omitempty"`
	// The unique ID for the capture. **Nullable** for Transactions Details.
	ID *string `json:"id,omitempty"`
	// The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs.
	MerchantEventID *string                `json:"merchant_event_id,omitempty"`
	Metadata        map[string]string      `json:"metadata,omitempty"`
	Splits          *TransactionSplitsView `json:"splits,omitempty"`
	// The status of the capture. **Nullable** for Transactions Details.
	Status *CaptureStatus `json:"status,omitempty"`
}

func (o *CreditCardCaptureView) GetAmount() *AmountView {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *CreditCardCaptureView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreditCardCaptureView) GetMerchantEventID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantEventID
}

func (o *CreditCardCaptureView) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *CreditCardCaptureView) GetSplits() *TransactionSplitsView {
	if o == nil {
		return nil
	}
	return o.Splits
}

func (o *CreditCardCaptureView) GetStatus() *CaptureStatus {
	if o == nil {
		return nil
	}
	return o.Status
}
