// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// EmailStatus - This is the status of the contact method.
type EmailStatus string

const (
	EmailStatusActive   EmailStatus = "active"
	EmailStatusPending  EmailStatus = "pending"
	EmailStatusInactive EmailStatus = "inactive"
)

func (e EmailStatus) ToPointer() *EmailStatus {
	return &e
}

func (e *EmailStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "pending":
		fallthrough
	case "inactive":
		*e = EmailStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EmailStatus: %v", v)
	}
}
