// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Emails - An object of user email.
type Emails struct {
	// An email address.
	Address *string `json:"address,omitempty"`
	// This is the ID for the email address associated with the shopper.
	ID *string `json:"id,omitempty"`
	// This is the priority of the contact method. This field's contents are not displayed in the transaction details view.
	Priority *EmailPriority `json:"priority,omitempty"`
	// This is the status of the contact method.
	Status *EmailStatus `json:"status,omitempty"`
}

func (o *Emails) GetAddress() *string {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *Emails) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Emails) GetPriority() *EmailPriority {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *Emails) GetStatus() *EmailStatus {
	if o == nil {
		return nil
	}
	return o.Status
}
