// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ErrorsOauthServerResponse - Invalid request to OAuth Token.
type ErrorsOauthServerResponse struct {
	Error            *string `json:"error,omitempty"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

func (o *ErrorsOauthServerResponse) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ErrorsOauthServerResponse) GetErrorDescription() *string {
	if o == nil {
		return nil
	}
	return o.ErrorDescription
}
