// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/utils"
	"time"
)

type ICartShipmentViewPackageDimension struct {
	Depth  *float64 `json:"depth,omitempty"`
	Height *float64 `json:"height,omitempty"`
	Unit   *string  `json:"unit,omitempty"`
	Width  *float64 `json:"width,omitempty"`
}

func (o *ICartShipmentViewPackageDimension) GetDepth() *float64 {
	if o == nil {
		return nil
	}
	return o.Depth
}

func (o *ICartShipmentViewPackageDimension) GetHeight() *float64 {
	if o == nil {
		return nil
	}
	return o.Height
}

func (o *ICartShipmentViewPackageDimension) GetUnit() *string {
	if o == nil {
		return nil
	}
	return o.Unit
}

func (o *ICartShipmentViewPackageDimension) GetWidth() *float64 {
	if o == nil {
		return nil
	}
	return o.Width
}

type ICartShipmentView struct {
	// The carrier used to deliver the shipment.
	Carrier               *string               `json:"carrier,omitempty"`
	Cost                  *AmountView           `json:"cost,omitempty"`
	Default               *bool                 `json:"default,omitempty"`
	Description           []IDescriptionPart    `json:"description,omitempty"`
	DescriptionTooltips   []IDescriptionTooltip `json:"description_tooltips,omitempty"`
	EstimatedDeliveryDate *time.Time            `json:"estimated_delivery_date,omitempty"`
	// Used to determine whether a shipment has been expedited or not.
	Expedited *bool `json:"expedited,omitempty"`
	// Defines which gift options are hidden.
	GiftOptions      *GiftOptionView                    `json:"gift_options,omitempty"`
	ID               *string                            `json:"id,omitempty"`
	PackageDimension *ICartShipmentViewPackageDimension `json:"package_dimension,omitempty"`
	PackageType      *string                            `json:"package_type,omitempty"`
	PackageWeight    *IWeight                           `json:"package_weight,omitempty"`
	Reference        *string                            `json:"reference,omitempty"`
	Service          *string                            `json:"service,omitempty"`
	// The address object returned in the response.
	ShippingAddress *AddressView `json:"shipping_address,omitempty"`
	ShippingMethod  *string      `json:"shipping_method,omitempty"`
	Signature       *string      `json:"signature,omitempty"`
	TaxAmount       *AmountView  `json:"tax_amount,omitempty"`
	TotalWeight     *IWeight     `json:"total_weight,omitempty"`
	Type            *string      `json:"type,omitempty"`
}

func (i ICartShipmentView) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ICartShipmentView) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ICartShipmentView) GetCarrier() *string {
	if o == nil {
		return nil
	}
	return o.Carrier
}

func (o *ICartShipmentView) GetCost() *AmountView {
	if o == nil {
		return nil
	}
	return o.Cost
}

func (o *ICartShipmentView) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *ICartShipmentView) GetDescription() []IDescriptionPart {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ICartShipmentView) GetDescriptionTooltips() []IDescriptionTooltip {
	if o == nil {
		return nil
	}
	return o.DescriptionTooltips
}

func (o *ICartShipmentView) GetEstimatedDeliveryDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.EstimatedDeliveryDate
}

func (o *ICartShipmentView) GetExpedited() *bool {
	if o == nil {
		return nil
	}
	return o.Expedited
}

func (o *ICartShipmentView) GetGiftOptions() *GiftOptionView {
	if o == nil {
		return nil
	}
	return o.GiftOptions
}

func (o *ICartShipmentView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ICartShipmentView) GetPackageDimension() *ICartShipmentViewPackageDimension {
	if o == nil {
		return nil
	}
	return o.PackageDimension
}

func (o *ICartShipmentView) GetPackageType() *string {
	if o == nil {
		return nil
	}
	return o.PackageType
}

func (o *ICartShipmentView) GetPackageWeight() *IWeight {
	if o == nil {
		return nil
	}
	return o.PackageWeight
}

func (o *ICartShipmentView) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *ICartShipmentView) GetService() *string {
	if o == nil {
		return nil
	}
	return o.Service
}

func (o *ICartShipmentView) GetShippingAddress() *AddressView {
	if o == nil {
		return nil
	}
	return o.ShippingAddress
}

func (o *ICartShipmentView) GetShippingMethod() *string {
	if o == nil {
		return nil
	}
	return o.ShippingMethod
}

func (o *ICartShipmentView) GetSignature() *string {
	if o == nil {
		return nil
	}
	return o.Signature
}

func (o *ICartShipmentView) GetTaxAmount() *AmountView {
	if o == nil {
		return nil
	}
	return o.TaxAmount
}

func (o *ICartShipmentView) GetTotalWeight() *IWeight {
	if o == nil {
		return nil
	}
	return o.TotalWeight
}

func (o *ICartShipmentView) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
