// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IDescriptionPart struct {
	Content *string `json:"content,omitempty"`
	IsHTML  *bool   `json:"is_html,omitempty"`
}

func (o *IDescriptionPart) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *IDescriptionPart) GetIsHTML() *bool {
	if o == nil {
		return nil
	}
	return o.IsHTML
}
