// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InStoreCartShipmentDistanceUnit string

const (
	InStoreCartShipmentDistanceUnitKm   InStoreCartShipmentDistanceUnit = "km"
	InStoreCartShipmentDistanceUnitMile InStoreCartShipmentDistanceUnit = "mile"
)

func (e InStoreCartShipmentDistanceUnit) ToPointer() *InStoreCartShipmentDistanceUnit {
	return &e
}

func (e *InStoreCartShipmentDistanceUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "km":
		fallthrough
	case "mile":
		*e = InStoreCartShipmentDistanceUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InStoreCartShipmentDistanceUnit: %v", v)
	}
}

type InStoreCartShipment struct {
	// A cart that is being prepared for shipment
	CartShipment *CartShipment `json:"cart_shipment,omitempty"`
	// Shipment option description.
	Description  *string                          `json:"description,omitempty"`
	Distance     *float64                         `json:"distance,omitempty"`
	DistanceUnit *InStoreCartShipmentDistanceUnit `json:"distance_unit,omitempty"`
	// The Address object is used for billing, shipping, and physical store address use cases.
	InStorePickupAddress *Address `json:"in_store_pickup_address,omitempty"`
	PickupWindowClose    *int64   `json:"pickup_window_close,omitempty"`
	PickupWindowOpen     *int64   `json:"pickup_window_open,omitempty"`
	// The local store's name where the item can be picked up.
	StoreName *string `json:"store_name,omitempty"`
}

func (o *InStoreCartShipment) GetCartShipment() *CartShipment {
	if o == nil {
		return nil
	}
	return o.CartShipment
}

func (o *InStoreCartShipment) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *InStoreCartShipment) GetDistance() *float64 {
	if o == nil {
		return nil
	}
	return o.Distance
}

func (o *InStoreCartShipment) GetDistanceUnit() *InStoreCartShipmentDistanceUnit {
	if o == nil {
		return nil
	}
	return o.DistanceUnit
}

func (o *InStoreCartShipment) GetInStorePickupAddress() *Address {
	if o == nil {
		return nil
	}
	return o.InStorePickupAddress
}

func (o *InStoreCartShipment) GetPickupWindowClose() *int64 {
	if o == nil {
		return nil
	}
	return o.PickupWindowClose
}

func (o *InStoreCartShipment) GetPickupWindowOpen() *int64 {
	if o == nil {
		return nil
	}
	return o.PickupWindowOpen
}

func (o *InStoreCartShipment) GetStoreName() *string {
	if o == nil {
		return nil
	}
	return o.StoreName
}
