// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MerchantDivisionSummaryViewHookType string

const (
	MerchantDivisionSummaryViewHookTypeOne   MerchantDivisionSummaryViewHookType = "1"
	MerchantDivisionSummaryViewHookTypeTwo   MerchantDivisionSummaryViewHookType = "2"
	MerchantDivisionSummaryViewHookTypeThree MerchantDivisionSummaryViewHookType = "3"
	MerchantDivisionSummaryViewHookTypeFour  MerchantDivisionSummaryViewHookType = "4"
	MerchantDivisionSummaryViewHookTypeFive  MerchantDivisionSummaryViewHookType = "5"
	MerchantDivisionSummaryViewHookTypeSix   MerchantDivisionSummaryViewHookType = "6"
)

func (e MerchantDivisionSummaryViewHookType) ToPointer() *MerchantDivisionSummaryViewHookType {
	return &e
}

func (e *MerchantDivisionSummaryViewHookType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "2":
		fallthrough
	case "3":
		fallthrough
	case "4":
		fallthrough
	case "5":
		fallthrough
	case "6":
		*e = MerchantDivisionSummaryViewHookType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MerchantDivisionSummaryViewHookType: %v", v)
	}
}

type MerchantDivisionSummaryView struct {
	AccountPageURL                   *string                              `json:"account_page_url,omitempty"`
	APIBaseDomainURL                 *string                              `json:"api_base_domain_url,omitempty"`
	BaseDomainURL                    *string                              `json:"base_domain_url,omitempty"`
	ConfirmationRedirectURL          *string                              `json:"confirmation_redirect_url,omitempty"`
	CreateOrderURL                   *string                              `json:"create_order_url,omitempty"`
	DebugURL                         *string                              `json:"debug_url,omitempty"`
	Description                      *string                              `json:"description,omitempty"`
	DisplayName                      *string                              `json:"display_name,omitempty"`
	GetAccountURL                    *string                              `json:"get_account_url,omitempty"`
	HookType                         *MerchantDivisionSummaryViewHookType `json:"hook_type,omitempty"`
	HookURL                          *string                              `json:"hook_url,omitempty"`
	ID                               *string                              `json:"id,omitempty"`
	IsUniversalMerchantAPI           *bool                                `json:"is_universal_merchant_api,omitempty"`
	IsWebhooksV2                     *bool                                `json:"is_webhooks_v2,omitempty"`
	Logo                             *MerchantDivisionLogoView            `json:"logo,omitempty"`
	LogoDashboard                    *MerchantDivisionLogoView            `json:"logo_dashboard,omitempty"`
	MerchantID                       *string                              `json:"merchant_id,omitempty"`
	MobileAppDomainURL               *string                              `json:"mobile_app_domain_url,omitempty"`
	OauthLogoutURL                   *string                              `json:"oauth_logout_url,omitempty"`
	OauthRedirectURL                 *string                              `json:"oauth_redirect_url,omitempty"`
	Platform                         *string                              `json:"platform,omitempty"`
	PluginConfigURL                  *string                              `json:"plugin_config_url,omitempty"`
	PrivacyPolicyURL                 *string                              `json:"privacy_policy_url,omitempty"`
	ProductInfoURL                   *string                              `json:"product_info_url,omitempty"`
	PublicID                         *string                              `json:"public_id,omitempty"`
	RemoteApiurl                     *string                              `json:"remote_apiurl,omitempty"`
	ShippingAndTaxURL                *string                              `json:"shipping_and_tax_url,omitempty"`
	ShippingURL                      *string                              `json:"shipping_url,omitempty"`
	Status                           *string                              `json:"status,omitempty"`
	TaxURL                           *string                              `json:"tax_url,omitempty"`
	TermsOfServiceURL                *string                              `json:"terms_of_service_url,omitempty"`
	UniversalMerchantAPIURL          *string                              `json:"universal_merchant_api_url,omitempty"`
	UpdateCartURL                    *string                              `json:"update_cart_url,omitempty"`
	UseAsyncRefundsAmazonPay         *bool                                `json:"use_async_refunds_amazon_pay,omitempty"`
	UseAsyncRefundsPaypal            *bool                                `json:"use_async_refunds_paypal,omitempty"`
	ValidateAdditionalAccountDataURL *string                              `json:"validate_additional_account_data_url,omitempty"`
}

func (o *MerchantDivisionSummaryView) GetAccountPageURL() *string {
	if o == nil {
		return nil
	}
	return o.AccountPageURL
}

func (o *MerchantDivisionSummaryView) GetAPIBaseDomainURL() *string {
	if o == nil {
		return nil
	}
	return o.APIBaseDomainURL
}

func (o *MerchantDivisionSummaryView) GetBaseDomainURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseDomainURL
}

func (o *MerchantDivisionSummaryView) GetConfirmationRedirectURL() *string {
	if o == nil {
		return nil
	}
	return o.ConfirmationRedirectURL
}

func (o *MerchantDivisionSummaryView) GetCreateOrderURL() *string {
	if o == nil {
		return nil
	}
	return o.CreateOrderURL
}

func (o *MerchantDivisionSummaryView) GetDebugURL() *string {
	if o == nil {
		return nil
	}
	return o.DebugURL
}

func (o *MerchantDivisionSummaryView) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *MerchantDivisionSummaryView) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *MerchantDivisionSummaryView) GetGetAccountURL() *string {
	if o == nil {
		return nil
	}
	return o.GetAccountURL
}

func (o *MerchantDivisionSummaryView) GetHookType() *MerchantDivisionSummaryViewHookType {
	if o == nil {
		return nil
	}
	return o.HookType
}

func (o *MerchantDivisionSummaryView) GetHookURL() *string {
	if o == nil {
		return nil
	}
	return o.HookURL
}

func (o *MerchantDivisionSummaryView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MerchantDivisionSummaryView) GetIsUniversalMerchantAPI() *bool {
	if o == nil {
		return nil
	}
	return o.IsUniversalMerchantAPI
}

func (o *MerchantDivisionSummaryView) GetIsWebhooksV2() *bool {
	if o == nil {
		return nil
	}
	return o.IsWebhooksV2
}

func (o *MerchantDivisionSummaryView) GetLogo() *MerchantDivisionLogoView {
	if o == nil {
		return nil
	}
	return o.Logo
}

func (o *MerchantDivisionSummaryView) GetLogoDashboard() *MerchantDivisionLogoView {
	if o == nil {
		return nil
	}
	return o.LogoDashboard
}

func (o *MerchantDivisionSummaryView) GetMerchantID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantID
}

func (o *MerchantDivisionSummaryView) GetMobileAppDomainURL() *string {
	if o == nil {
		return nil
	}
	return o.MobileAppDomainURL
}

func (o *MerchantDivisionSummaryView) GetOauthLogoutURL() *string {
	if o == nil {
		return nil
	}
	return o.OauthLogoutURL
}

func (o *MerchantDivisionSummaryView) GetOauthRedirectURL() *string {
	if o == nil {
		return nil
	}
	return o.OauthRedirectURL
}

func (o *MerchantDivisionSummaryView) GetPlatform() *string {
	if o == nil {
		return nil
	}
	return o.Platform
}

func (o *MerchantDivisionSummaryView) GetPluginConfigURL() *string {
	if o == nil {
		return nil
	}
	return o.PluginConfigURL
}

func (o *MerchantDivisionSummaryView) GetPrivacyPolicyURL() *string {
	if o == nil {
		return nil
	}
	return o.PrivacyPolicyURL
}

func (o *MerchantDivisionSummaryView) GetProductInfoURL() *string {
	if o == nil {
		return nil
	}
	return o.ProductInfoURL
}

func (o *MerchantDivisionSummaryView) GetPublicID() *string {
	if o == nil {
		return nil
	}
	return o.PublicID
}

func (o *MerchantDivisionSummaryView) GetRemoteApiurl() *string {
	if o == nil {
		return nil
	}
	return o.RemoteApiurl
}

func (o *MerchantDivisionSummaryView) GetShippingAndTaxURL() *string {
	if o == nil {
		return nil
	}
	return o.ShippingAndTaxURL
}

func (o *MerchantDivisionSummaryView) GetShippingURL() *string {
	if o == nil {
		return nil
	}
	return o.ShippingURL
}

func (o *MerchantDivisionSummaryView) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *MerchantDivisionSummaryView) GetTaxURL() *string {
	if o == nil {
		return nil
	}
	return o.TaxURL
}

func (o *MerchantDivisionSummaryView) GetTermsOfServiceURL() *string {
	if o == nil {
		return nil
	}
	return o.TermsOfServiceURL
}

func (o *MerchantDivisionSummaryView) GetUniversalMerchantAPIURL() *string {
	if o == nil {
		return nil
	}
	return o.UniversalMerchantAPIURL
}

func (o *MerchantDivisionSummaryView) GetUpdateCartURL() *string {
	if o == nil {
		return nil
	}
	return o.UpdateCartURL
}

func (o *MerchantDivisionSummaryView) GetUseAsyncRefundsAmazonPay() *bool {
	if o == nil {
		return nil
	}
	return o.UseAsyncRefundsAmazonPay
}

func (o *MerchantDivisionSummaryView) GetUseAsyncRefundsPaypal() *bool {
	if o == nil {
		return nil
	}
	return o.UseAsyncRefundsPaypal
}

func (o *MerchantDivisionSummaryView) GetValidateAdditionalAccountDataURL() *string {
	if o == nil {
		return nil
	}
	return o.ValidateAdditionalAccountDataURL
}
