// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MerchantOnboardingStatusCode string

const (
	MerchantOnboardingStatusCodeNewMerchant               MerchantOnboardingStatusCode = "new_merchant"
	MerchantOnboardingStatusCodeUserCreated               MerchantOnboardingStatusCode = "user_created"
	MerchantOnboardingStatusCodeFormFilled                MerchantOnboardingStatusCode = "form_filled"
	MerchantOnboardingStatusCodeIntegrationDone           MerchantOnboardingStatusCode = "integration_done"
	MerchantOnboardingStatusCodeLegacy                    MerchantOnboardingStatusCode = "legacy"
	MerchantOnboardingStatusCodeProcessorSettingsReceived MerchantOnboardingStatusCode = "processor_settings_received"
)

func (e MerchantOnboardingStatusCode) ToPointer() *MerchantOnboardingStatusCode {
	return &e
}

func (e *MerchantOnboardingStatusCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "new_merchant":
		fallthrough
	case "user_created":
		fallthrough
	case "form_filled":
		fallthrough
	case "integration_done":
		fallthrough
	case "legacy":
		fallthrough
	case "processor_settings_received":
		*e = MerchantOnboardingStatusCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MerchantOnboardingStatusCode: %v", v)
	}
}
