// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MerchantDivisionLogoView struct {
	Domain   *string `json:"domain,omitempty"`
	Resource *string `json:"resource,omitempty"`
}

func (o *MerchantDivisionLogoView) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *MerchantDivisionLogoView) GetResource() *string {
	if o == nil {
		return nil
	}
	return o.Resource
}
