// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OrderDecision - Decision and score for an order.
type OrderDecision struct {
	// The top 5 factors of the fraud decision.
	DecisionFactors []RiskDecisionFactorYml `json:"decision_factors,omitempty"`
	// The total fraud risk score of the order.
	Score *int64 `json:"score,omitempty"`
}

func (o *OrderDecision) GetDecisionFactors() []RiskDecisionFactorYml {
	if o == nil {
		return nil
	}
	return o.DecisionFactors
}

func (o *OrderDecision) GetScore() *int64 {
	if o == nil {
		return nil
	}
	return o.Score
}
