// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrderDecisionDetailsView struct {
	DecisionFactors []string `json:"decision_factors,omitempty"`
	Score           *float64 `json:"score,omitempty"`
}

func (o *OrderDecisionDetailsView) GetDecisionFactors() []string {
	if o == nil {
		return nil
	}
	return o.DecisionFactors
}

func (o *OrderDecisionDetailsView) GetScore() *float64 {
	if o == nil {
		return nil
	}
	return o.Score
}
