// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PhonesWithCountryCode - A phone number with country code.
type PhonesWithCountryCode struct {
	// A phone number's country code.
	CountryCode *string `json:"country_code,omitempty"`
	// This is the ID for the phone number associated with the shopper.
	ID *string `json:"id,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	Number *string `json:"number,omitempty"`
	// This is the priority of the contact method. This field's contents are not displayed in the transaction details view.
	Priority *PhonePriority `json:"priority,omitempty"`
	// This is the status of the contact method.
	Status *PhoneStatus `json:"status,omitempty"`
}

func (o *PhonesWithCountryCode) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *PhonesWithCountryCode) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PhonesWithCountryCode) GetNumber() *string {
	if o == nil {
		return nil
	}
	return o.Number
}

func (o *PhonesWithCountryCode) GetPriority() *PhonePriority {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *PhonesWithCountryCode) GetStatus() *PhoneStatus {
	if o == nil {
		return nil
	}
	return o.Status
}
