// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Priority - Describes the card's priority.
type Priority string

const (
	PriorityPrimary Priority = "primary"
	PriorityListed  Priority = "listed"
)

func (e Priority) ToPointer() *Priority {
	return &e
}

func (e *Priority) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "listed":
		*e = Priority(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Priority: %v", v)
	}
}
