// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ProcessingInitiator - Defines which payment method was used to initiate the transaction.
type ProcessingInitiator string

const (
	ProcessingInitiatorInitialCardOnFile         ProcessingInitiator = "initial_card_on_file"
	ProcessingInitiatorInitialRecurring          ProcessingInitiator = "initial_recurring"
	ProcessingInitiatorStoredCardholderInitiated ProcessingInitiator = "stored_cardholder_initiated"
	ProcessingInitiatorStoredMerchantInitiated   ProcessingInitiator = "stored_merchant_initiated"
	ProcessingInitiatorFollowingRecurring        ProcessingInitiator = "following_recurring"
	ProcessingInitiatorCardholderInitiated       ProcessingInitiator = "cardholder_initiated"
	ProcessingInitiatorRecurring                 ProcessingInitiator = "recurring"
)

func (e ProcessingInitiator) ToPointer() *ProcessingInitiator {
	return &e
}

func (e *ProcessingInitiator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initial_card_on_file":
		fallthrough
	case "initial_recurring":
		fallthrough
	case "stored_cardholder_initiated":
		fallthrough
	case "stored_merchant_initiated":
		fallthrough
	case "following_recurring":
		fallthrough
	case "cardholder_initiated":
		fallthrough
	case "recurring":
		*e = ProcessingInitiator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProcessingInitiator: %v", v)
	}
}
