// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RequestStatus string

const (
	RequestStatusReviewed    RequestStatus = "reviewed"
	RequestStatusNeedsReview RequestStatus = "needs_review"
	RequestStatusUnknown     RequestStatus = "unknown"
)

func (e RequestStatus) ToPointer() *RequestStatus {
	return &e
}

func (e *RequestStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reviewed":
		fallthrough
	case "needs_review":
		fallthrough
	case "unknown":
		*e = RequestStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RequestStatus: %v", v)
	}
}
