// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ReviewTicketView struct {
	ID              *string  `json:"id,omitempty"`
	RequestDeadline *float64 `json:"request_deadline,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

func (o *ReviewTicketView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ReviewTicketView) GetRequestDeadline() *float64 {
	if o == nil {
		return nil
	}
	return o.RequestDeadline
}

func (o *ReviewTicketView) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
