// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RiskInsightsYml - Displays fraud decisioning insights based on key factors. This information can either be forwarded via a `risk_insights` transaction webhook type or be polled by sending a `GET` request to Bolt's [transactions endpoint](/api-bolt/#operation/transaction-details).
type RiskInsightsYml struct {
	// Must be set to `true` to receive fraud insights.
	Available *bool `json:"available,omitempty"`
	// The top 5 factors of the fraud decision.
	DecisionFactors []RiskDecisionFactorYml `json:"decision_factors,omitempty"`
	// The total [fraud score](/merchants/references/policies/fraud-review/#fraud-scoring).
	//
	FraudProbability         *int64            `json:"fraud_probability,omitempty"`
	PaymentInstrumentFactors map[string]string `json:"payment_instrument_factors,omitempty"`
}

func (o *RiskInsightsYml) GetAvailable() *bool {
	if o == nil {
		return nil
	}
	return o.Available
}

func (o *RiskInsightsYml) GetDecisionFactors() []RiskDecisionFactorYml {
	if o == nil {
		return nil
	}
	return o.DecisionFactors
}

func (o *RiskInsightsYml) GetFraudProbability() *int64 {
	if o == nil {
		return nil
	}
	return o.FraudProbability
}

func (o *RiskInsightsYml) GetPaymentInstrumentFactors() map[string]string {
	if o == nil {
		return nil
	}
	return o.PaymentInstrumentFactors
}
