// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RiskReviewStatus - Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team.
type RiskReviewStatus string

const (
	RiskReviewStatusUnknown     RiskReviewStatus = "unknown"
	RiskReviewStatusNeedsReview RiskReviewStatus = "needs_review"
	RiskReviewStatusReviewed    RiskReviewStatus = "reviewed"
)

func (e RiskReviewStatus) ToPointer() *RiskReviewStatus {
	return &e
}

func (e *RiskReviewStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unknown":
		fallthrough
	case "needs_review":
		fallthrough
	case "reviewed":
		*e = RiskReviewStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RiskReviewStatus: %v", v)
	}
}
