// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RiskModelExternalResultView struct {
	Available *bool `json:"available,omitempty"`
	// Used to list a total of up to 5 decision factors used by the risk model to determine the risk analysis result.
	DecisionFactors          []string          `json:"decision_factors,omitempty"`
	FraudProbability         *float64          `json:"fraud_probability,omitempty"`
	PaymentInstrumentFactors map[string]string `json:"payment_instrument_factors,omitempty"`
}

func (o *RiskModelExternalResultView) GetAvailable() *bool {
	if o == nil {
		return nil
	}
	return o.Available
}

func (o *RiskModelExternalResultView) GetDecisionFactors() []string {
	if o == nil {
		return nil
	}
	return o.DecisionFactors
}

func (o *RiskModelExternalResultView) GetFraudProbability() *float64 {
	if o == nil {
		return nil
	}
	return o.FraudProbability
}

func (o *RiskModelExternalResultView) GetPaymentInstrumentFactors() map[string]string {
	if o == nil {
		return nil
	}
	return o.PaymentInstrumentFactors
}
