// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/types"
	"github.com/speakeasy-sdks/bolt-embedded-go/pkg/utils"
)

// SavedPaypalAccountView - Saved PayPal account details.
type SavedPaypalAccountView struct {
	// The email associated with a shopper's saved PayPal account.
	Description *string `json:"description,omitempty"`
	// The ID of the payment method associated with the Shopper's account.
	ID *string `json:"id,omitempty"`
	// A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).
	//
	Metadata *Metadata `json:"metadata,omitempty"`
	// Type field indicates this is a saved PayPal to differentiate it from a saved card.
	type_ *string `const:"paypal" json:"type,omitempty"`
}

func (s SavedPaypalAccountView) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedPaypalAccountView) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *SavedPaypalAccountView) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *SavedPaypalAccountView) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SavedPaypalAccountView) GetMetadata() *Metadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *SavedPaypalAccountView) GetType() *string {
	return types.String("paypal")
}
