// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	OAuth   *string `security:"scheme,type=oauth2,name=Authorization"`
	XAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *Security) GetOAuth() *string {
	if o == nil {
		return nil
	}
	return o.OAuth
}

func (o *Security) GetXAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.XAPIKey
}
