// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TransactionOperationalProcessor struct {
	// The processor used. **Nullable** for Transactions Details.
	Processor TransactionProcessor `json:"processor"`
	// The processor's status. Only `primary` and `active` processor are displayed.
	Status TransactionProcessorStatus `json:"status"`
}

func (o *TransactionOperationalProcessor) GetProcessor() TransactionProcessor {
	if o == nil {
		return TransactionProcessor("")
	}
	return o.Processor
}

func (o *TransactionOperationalProcessor) GetStatus() TransactionProcessorStatus {
	if o == nil {
		return TransactionProcessorStatus("")
	}
	return o.Status
}
