// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserIdentifier - The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number.
type UserIdentifier struct {
	Artifact *string `json:"artifact,omitempty"`
	// An email address.
	Email *string `json:"email,omitempty"`
	// The ID associated with the identifying email address for this account.
	EmailID *string `json:"email_id,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	Phone string `json:"phone"`
	// The ID associated with the identifying phone number for this account.
	PhoneID *string `json:"phone_id,omitempty"`
}

func (o *UserIdentifier) GetArtifact() *string {
	if o == nil {
		return nil
	}
	return o.Artifact
}

func (o *UserIdentifier) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UserIdentifier) GetEmailID() *string {
	if o == nil {
		return nil
	}
	return o.EmailID
}

func (o *UserIdentifier) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}

func (o *UserIdentifier) GetPhoneID() *string {
	if o == nil {
		return nil
	}
	return o.PhoneID
}
