// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// WebhooksType - [Webhook events](https://help.bolt.com/developers/guides/webhooks/#transaction-hook-types) that trigger a notification to the URL.  **Note**:`newsletter_subscription` is only for merchant use cases.
type WebhooksType string

const (
	WebhooksTypePayment                WebhooksType = "payment"
	WebhooksTypeCredit                 WebhooksType = "credit"
	WebhooksTypeCapture                WebhooksType = "capture"
	WebhooksTypeVoid                   WebhooksType = "void"
	WebhooksTypeAuth                   WebhooksType = "auth"
	WebhooksTypePending                WebhooksType = "pending"
	WebhooksTypeRejectedIrreversible   WebhooksType = "rejected_irreversible"
	WebhooksTypeRejectedReversible     WebhooksType = "rejected_reversible"
	WebhooksTypeFailedPayment          WebhooksType = "failed_payment"
	WebhooksTypeNewsletterSubscription WebhooksType = "newsletter_subscription"
	WebhooksTypeRiskInsights           WebhooksType = "risk_insights"
	WebhooksTypeCreditCardDeleted      WebhooksType = "credit_card_deleted"
)

func (e WebhooksType) ToPointer() *WebhooksType {
	return &e
}

func (e *WebhooksType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "payment":
		fallthrough
	case "credit":
		fallthrough
	case "capture":
		fallthrough
	case "void":
		fallthrough
	case "auth":
		fallthrough
	case "pending":
		fallthrough
	case "rejected_irreversible":
		fallthrough
	case "rejected_reversible":
		fallthrough
	case "failed_payment":
		fallthrough
	case "newsletter_subscription":
		fallthrough
	case "risk_insights":
		fallthrough
	case "credit_card_deleted":
		*e = WebhooksType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhooksType: %v", v)
	}
}
